// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjRR0HUA0PlmAI5IRMop_mZnL4yInHnJE',
    appId: '1:479439767117:web:5900edeaa210410e44fe04',
    messagingSenderId: '479439767117',
    projectId: 'carpooling-app-51cb5',
    authDomain: 'carpooling-app-51cb5.firebaseapp.com',
    storageBucket: 'carpooling-app-51cb5.firebasestorage.app',
    measurementId: 'G-RD228R4GE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnoZGhkuBnMbqvSRpICJpfNts1tk33jrw',
    appId: '1:479439767117:android:28fd2f415ca00d6644fe04',
    messagingSenderId: '479439767117',
    projectId: 'carpooling-app-51cb5',
    storageBucket: 'carpooling-app-51cb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBWjr91iv15KSlxmD_wZPTVskKxERjTLU',
    appId: '1:479439767117:ios:060eafef6e0096f044fe04',
    messagingSenderId: '479439767117',
    projectId: 'carpooling-app-51cb5',
    storageBucket: 'carpooling-app-51cb5.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBWjr91iv15KSlxmD_wZPTVskKxERjTLU',
    appId: '1:479439767117:ios:060eafef6e0096f044fe04',
    messagingSenderId: '479439767117',
    projectId: 'carpooling-app-51cb5',
    storageBucket: 'carpooling-app-51cb5.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjRR0HUA0PlmAI5IRMop_mZnL4yInHnJE',
    appId: '1:479439767117:web:5f924bb02d5d92ba44fe04',
    messagingSenderId: '479439767117',
    projectId: 'carpooling-app-51cb5',
    authDomain: 'carpooling-app-51cb5.firebaseapp.com',
    storageBucket: 'carpooling-app-51cb5.firebasestorage.app',
    measurementId: 'G-ZK0L4QGJES',
  );
}
